module.exports.orderStatus = {
  WAITING_FOR_PAYMENT: "WAITING_FOR_PAYMENT",
  PAYMENT_EXPIRED: "PAYMENT_EXPIRED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  COMPLETED: "COMPLETED",
  CANCELED: "CANCELED",
}
